debug: true
spring:
  datasource:
    url: jdbc:mysql://39.106.92.253:3306/learndb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: HelloWorld_1989
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.interview.model